printf("Loading defines...")
-- Some pseudo-defines
TRADESKILL_ALCHEMY = 1
TRADESKILL_BLACKSMITHING = 2
TRADESKILL_ALCHEMY =              1
TRADESKILL_BLACKSMITHING =        2
TRADESKILL_COOKING =              3
TRADESKILL_ENCHANTING =           4
TRADESKILL_ENGINEERING =          5
TRADESKILL_FIRSTAID =             6
TRADESKILL_HERBALISM =            7
TRADESKILL_LEATHERWORKING =       8
TRADESKILL_POISONS =              9
TRADESKILL_TAILORING =            10
TRADESKILL_MINING = 		    11
TRADESKILL_FISHING = 		    12
TRADESKILL_SKINNING = 		    13

TRADESKILL_LEVEL_NONE =           0
TRADESKILL_LEVEL_APPRENTICE =     1
TRADESKILL_LEVEL_JOURNEYMAN =     2
TRADESKILL_LEVEL_EXPERT =         3
TRADESKILL_LEVEL_ARTISAN =        4

-- Gossip defines
GOSSIP_ACTION_TRADE =   1
GOSSIP_ACTION_TRAIN =   2
GOSSIP_ACTION_TAXI =    3
GOSSIP_ACTION_GUILD =   4
GOSSIP_ACTION_BATTLE =  5
GOSSIP_ACTION_BANK =    6
GOSSIP_ACTION_INN =     7
GOSSIP_ACTION_HEAL =    8
GOSSIP_ACTION_TABARD =  9
GOSSIP_ACTION_AUCTION = 10
GOSSIP_ACTION_INN_INFO= 11
GOSSIP_ACTION_UNLEARN = 12
GOSSIP_ACTION_INFO_DEF= 1000

GOSSIP_SENDER_MAIN = 		1
GOSSIP_SENDER_INN_INFO = 	2
GOSSIP_SENDER_INFO = 		3
GOSSIP_SENDER_SEC_PROFTRAIN = 4
GOSSIP_SENDER_SEC_CLASSTRAIN= 5
GOSSIP_SENDER_SEC_BATTLEINFO= 6

-- How do I set this?
-- DEFAULT_GOSSIP_MESSAGE = 0xffffff
-- I dont know :)

printf("Defines loaded!")